### ISSUE TITLE
Test the use of MUI DataGrid

### ISSUE THREAD

**Issue by ACD03** [lucoenergia/conluz-web#33]
Examine the advantages of utilizing the MUI DataGrid over a conventional MUI Table

**Comment by viktorKhan** [comment]
When you create an issue and a branch for it, you can either create a branch directly from GitHub or link an already created branch from the section "Development"

![imagen](https://github.com/lucoenergia/conluz-web/assets/4686378/8aeff3fd-28a5-45c1-8dab-8d3e4054b42e)

Doing that, you could have all the info within the issue.

I've already linked the branch `feature/CONLUZWEB-33` as part of this issue.
